name: atlas-cli # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Command line interface for the MongoDB Atlas API # 79 char long summary
description: |
  This is a command line tool to create and manage MongoDB clusters in Atlas using the Atlas API.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  atlas-cli:
    # See 'snapcraft plugins'
    plugin: nodejs
    source: .
    nodejs-package-manager: npm
    nodejs-version: "10.16.3"
    build-packages: 
      - git

apps:
  atlas-cli: 
    command: atlas-cli
    plugs:
      - network
      - network-bind
      - network-control
